"""RulesScreen."""

from __future__ import annotations

from typing import ClassVar

from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Container, VerticalScroll
from textual.screen import ModalScreen
from textual.widgets import Static, TabbedContent, TabPane

from gameengine.core.audio import sound_manager
from gameengine.core.models import Day
from gameengine.ui.tui import rules_content
from gameengine.ui.tui.shared import (
    _B,
)
from gameengine.ui.tui.widgets import (
    EvidenceBoard,
    EvidenceState,
)


class RulesScreen(ModalScreen):
    """Documentation hub — day rules + per-tool reference.

    Five tabs: Rules · OSINT · Credentials · Logs · Steganography.
    Press 0 or Esc to dismiss.
    """

    BINDINGS: ClassVar[list[Binding]] = [
        Binding(_B["page_rules"], "dismiss_rules", "Close"),
        Binding("escape",         "dismiss_rules", "Close"),
    ]

    def __init__(self, day: Day, evidence_state: EvidenceState | None = None,
                 initial_tab: str | None = None,
                 scroll_memory: dict[str, float] | None = None,
                 unlocked_tools: set[str] | None = None) -> None:
        super().__init__()
        self._day = day
        # #50: which tab to open on, and where each tab was last scrolled to.
        # The screen is re-instantiated on every open (it's a ModalScreen that
        # gets dismissed, not hidden), so scroll state has to be owned by the
        # app and handed in — keeping it on the screen would reset it every time.
        self._initial_tab   = initial_tab
        self._scroll_memory = scroll_memory if scroll_memory is not None else {}
        # Progressive unlock: None (the default, and what every pre-#33-extension
        # caller still passes) means "no gating context" — every tab and rule
        # renders, same as before this parameter existed.
        self._unlocked_tools = unlocked_tools
        # Shared evidence record — lets the player flag evidence from the Rules
        # overlay too, so the board is always within reach.
        self._ev_board = (
            EvidenceBoard(evidence_state, "evidence-rules", "rules-evidence",
                          home_group="DOSSIER", unlocked_tools=unlocked_tools)
            if evidence_state is not None else None
        )

    def compose(self) -> ComposeResult:
        with Container(id="rules-modal"):
            yield Static("[b][#7dd3c0]HACKDOX  DOCUMENTATION HUB[/][/]", id="rules-title")
            with TabbedContent(id="rules-tabs"):
                with TabPane("Rules", id="tab-rules"), VerticalScroll():
                    yield Static(self._build_rules_text(), classes="rules-section")
                # #50: the dossier-tier reference split out of the Rules tab.
                with TabPane("Dossier", id="tab-dossier"), VerticalScroll():
                    yield Static(self._build_dossier_text(), classes="rules-section")
                with TabPane("OSINT", id="tab-osint"), VerticalScroll():
                    yield Static(self._build_osint_text(), classes="rules-section")
                with TabPane("Credentials", id="tab-creds"), VerticalScroll():
                    yield Static(self._build_creds_text(), classes="rules-section")
                with TabPane("Log Analysis", id="tab-logs"), VerticalScroll():
                    yield Static(self._build_logs_text(), classes="rules-section")
                with TabPane("Steganography", id="tab-stego"), VerticalScroll():
                    yield Static(self._build_stego_text(), classes="rules-section")
                if self._ev_board is not None:
                    with TabPane("Evidence", id="tab-evidence"):
                        yield self._ev_board
            yield Static(
                f"[dim]Tab/click to switch sections  ·  "
                f"Press [b]{_B['page_rules'].upper()}[/] or Esc to close[/]",
                id="rules-hint",
            )

    # ── Tab content builders ──────────────────────────────────────────

    # Issue #30: all tab content is generated by rules_content — a dynamic,
    # engine-derived builder set. Nothing here can drift from the code.

    def _build_rules_text(self) -> str:
        return rules_content.build_rules_text(self._day, self._unlocked_tools)

    def _build_dossier_text(self) -> str:
        return rules_content.build_dossier_text(self._day)

    def _build_osint_text(self) -> str:
        return rules_content.build_osint_text(self._day, self._unlocked_tools)

    def _build_creds_text(self) -> str:
        return rules_content.build_creds_text(self._day, self._unlocked_tools)

    def _build_logs_text(self) -> str:
        return rules_content.build_logs_text(self._day, self._unlocked_tools)

    def _build_stego_text(self) -> str:
        return rules_content.build_stego_text(self._day, self._unlocked_tools)

    def on_mount(self) -> None:
        """#50: open on the tab matching the page the player came from, and
        restore that tab's last scroll position."""
        sound_manager.play("rules_open")
        if self._initial_tab:
            try:
                self.query_one("#rules-tabs", TabbedContent).active = self._initial_tab
            except Exception:  # noqa: BLE001, S110 -- an unknown id would otherwise take
                # the whole overlay down; the default tab is a perfectly good fallback.
                pass
        self._restore_scroll()

    def _active_scroll(self) -> VerticalScroll | None:
        """The VerticalScroll inside the currently active TabPane."""
        try:
            tabs = self.query_one("#rules-tabs", TabbedContent)
            pane = tabs.get_pane(tabs.active)
            return pane.query(VerticalScroll).first()
        except Exception:  # noqa: BLE001 -- no active pane / no scrollable child yet;
            # None is a valid "nothing to scroll" answer for every caller of this helper.
            return None

    def _restore_scroll(self) -> None:
        tabs = self.query_one("#rules-tabs", TabbedContent)
        target = self._scroll_memory.get(tabs.active)
        view = self._active_scroll()
        if view is not None and target:
            # animate=False so the restore is instant rather than visibly
            # scrolling down from the top every time the overlay opens.
            view.scroll_to(y=target, animate=False)

    def _remember_scroll(self) -> None:
        tabs = self.query_one("#rules-tabs", TabbedContent)
        view = self._active_scroll()
        if view is not None:
            self._scroll_memory[tabs.active] = view.scroll_offset.y

    def on_tabbed_content_tab_activated(
            self, event: TabbedContent.TabActivated) -> None:
        # Restore the newly-shown tab's position. Its own offset was saved when
        # the player last switched away from or closed it.
        self._restore_scroll()

    def action_dismiss_rules(self) -> None:
        sound_manager.play("rules_close")
        self._remember_scroll()
        self.dismiss()
